# Apply MDM and QDM to CMIP6 daily temperatures
- Daily temperature data is loaded using the OSDF protocol and discovered using an intake-ESM catalog
- We apply three different bias-correction techniques to pairs of CMIP6 models, treating one of the models in the pair as pseudo-observations
- The bias-correction techniques are Moment Delta Mapping, Quantile Delta Mapping+ sort and a shift in DMT

In [ ]:
from matplotlib import pyplot as plt
import xarray as xr
import numpy as np
import dask_jobqueue
import dask
from dask.diagnostics import progress
from tqdm.autonotebook import tqdm
import cartopy.io.shapereader as shpreader
import cartopy.feature as cfeature
import intake
import fsspec
import xarray_regrid 
#import seaborn as sns
import s3fs
import cftime
import pandas as pd

/tmp/ipykernel_891395/417568950.py:6: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm

In [2]:
# Decide whether to re-calculate everything
RECALC = True
#
pi_year  = 1865
eoc_year = 2085
#
chic_lat  = 41.8781
chic_lon  = (360-87.6298)%360
ben_lat   = 12.9716
ben_lon   = 77.5946
#
lustre_scratch   = "/lustre/desc1/scratch/harshah"
gdex_url     =  'https://data.gdex.ucar.edu/'
catalog_url = gdex_url +  'd850001/catalogs/osdf/cmip6-aws/cmip6-osdf-zarr.json'
# catalog_url = 'https://cmip6-pds.s3.amazonaws.com/pangeo-cmip6.json'
gdex_data    = '/gdex/data/special_projects/harshah/osdf_data/'
#
tmean_path  = gdex_data + 'tmean/'
tmax_path   = gdex_data + 'tmax/'
tmin_path   = gdex_data + 'tmin/'

## Section 2: Select Dask Cluster
- Setting up a dask cluster. You will need to choose the type of cluster based on your use case.
- The default will be LocalCluster as that can run on any system.
- If running on NCAR's HPC i.e, Casper with a PBS Scheduler, set USE_PBS_SCHEDULER to True. Otherwise, set to False.

In [3]:
USE_PBS_SCHEDULER = False

If running on Jupyter server with Dask Gateway configured, set to True. Otherwise, set to False.

In [4]:
USE_DASK_GATEWAY = False

#### Python function for a PBS cluster

In [5]:
# Create a PBS cluster object
def get_pbs_cluster():
    """ Create cluster through dask_jobqueue.   
    """
    # Set up your sratch folder path
    username       = os.environ["USER"]
    glade_scratch  = "/glade/derecho/scratch/" + username
    print(glade_scratch)
    from dask_jobqueue import PBSCluster
    cluster = PBSCluster(
        job_name = 'dask-osdf-25',
        cores = 1,
        memory = '4GiB',
        processes = 1,
        local_directory = glade_scratch + '/dask/spill',
        log_directory = glade_scratch + '/dask/logs/',
        resource_spec = 'select=1:ncpus=1:mem=4GB',
        queue = 'casper',
        walltime = '3:00:00',
        #interface = 'ib0'
        interface = 'ext'
    )
    return cluster

#### Python function for a Gateway Cluster

In [6]:
def get_gateway_cluster():
    """ Create cluster through dask_gateway
    """
    from dask_gateway import Gateway

    gateway = Gateway()
    cluster = gateway.new_cluster()
    cluster.adapt(minimum=2, maximum=4)
    return cluster

#### Python function for a Local Cluster

In [7]:
def get_local_cluster():
    """ Create cluster using the Jupyter server's resources
    """
    from distributed import LocalCluster, performance_report
    cluster = LocalCluster()    

    return cluster

#### Python logic to select the Dask Cluster type
- This uses True/False boolean logic based on the variables set in the previous cells

In [8]:
# Obtain dask cluster in one of three ways

if USE_PBS_SCHEDULER:
    cluster = get_pbs_cluster()
elif USE_DASK_GATEWAY:
    cluster = get_gateway_cluster()
else:
    cluster = get_local_cluster()

# Connect to cluster
from distributed import Client
client = Client(cluster)

/home/ncote/miniforge3/envs/nb-env/lib/python3.13/site-packages/distributed/node.py:188: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 43323 instead
  warnings.warn(

In [9]:
cluster.scale(4)
client.wait_for_workers(4)
cluster

LocalCluster(6b438cfb, 'tcp://127.0.0.1:45017', workers=4, threads=8, memory=15.40 GiB)

In [10]:
# calculate global means
def get_lat_name(ds):
    for lat_name in ['lat', 'latitude']:
        if lat_name in ds.coords:
            return lat_name
    raise RuntimeError("Couldn't find a latitude coordinate")

def global_mean(ds):
    lat = ds[get_lat_name(ds)]
    weight = np.cos(np.deg2rad(lat))
    weight /= weight.mean()
    other_dims = set(ds.dims) - {'quantile'}
    return (ds * weight).mean(other_dims)

def detrend_data(ds, central_year):
    # Assumes that the ds has coordinates day, year and member.
    
    #Fit a linear fuction and extract slope
    pcoeffs = ds.polyfit(dim='year',deg=1)
    slope   = pcoeffs.polyfit_coefficients.sel(degree=1)
    
    #Calculate trend
    ds_trend   = slope*(ds['year']- central_year)
    
    #Detrend by subtracting the trend from the data
    ds_detrended = ds  - ds_trend
    
    return ds_detrended

## Section 2: Load Data

In [11]:
col = intake.open_esm_datastore(catalog_url)
col

In [12]:
var_name    = 'tas'
folder_path = tmean_path
variable    = ['tas'] #Other variables of interest: 'tasmax', 'tasmin'

In [13]:
# 2. Search for daily temperature 
expts = ['ssp370','historical']

query = dict(
    experiment_id=expts,
    table_id='day',
    variable_id= variable,
    member_id = 'r1i1p1f1',
    #activity_id = 'CMIP',
    
)

col_subset = col.search(require_all_on=["source_id"], **query)

col_subset.df.groupby("source_id")[["experiment_id", "variable_id", "table_id","member_id"]].nunique()

                   experiment_id  variable_id  table_id  member_id
source_id
ACCESS-CM2                     2            1         1          1
AWI-CM-1-1-MR                  2            1         1          1
BCC-CSM2-MR                    2            1         1          1
BCC-ESM1                       2            1         1          1
CESM2-WACCM                    2            1         1          1
CMCC-CM2-SR5                   2            1         1          1
CMCC-ESM2                      2            1         1          1
CanESM5                        2            1         1          1
EC-Earth3                      2            1         1          1
EC-Earth3-AerChem              2            1         1          1
EC-Earth3-Veg                  2            1         1          1
EC-Earth3-Veg-LR               2            1         1          1
FGOALS-g3                      2            1         1          1
GFDL-ESM4                      2            1         1          1
IITM-ESM                       2            1         1          1
INM-CM4-8                      2            1         1          1
INM-CM5-0                      2            1         1          1
IPSL-CM5A2-INCA                2            1         1          1
IPSL-CM6A-LR                   2            1         1          1
KACE-1-0-G                     2            1         1          1
MIROC6                         2            1         1          1
MPI-ESM-1-2-HAM                2            1         1          1
MPI-ESM1-2-HR                  2            1         1          1
MPI-ESM1-2-LR                  2            1         1          1
MRI-ESM2-0                     2            1         1          1
NorESM2-LM                     2            1         1          1
NorESM2-MM                     2            1         1          1

In [14]:
df = col_subset.df
# model_counts = df.groupby('source_id').size()
# print(model_counts)
df.head()

,activity_id,institution_id,source_id,experiment_id,member_id,table_id,variable_id,grid_label,zstore,dcpp_init_year,version
0,CMIP,CSIRO-ARCCSS,ACCESS-CM2,historical,r1i1p1f1,day,tas,gn,osdf:///aws-opendata/us-west-2/cmip6-pds/CMIP6...,<NA>,20191108
1,ScenarioMIP,CSIRO-ARCCSS,ACCESS-CM2,ssp370,r1i1p1f1,day,tas,gn,osdf:///aws-opendata/us-west-2/cmip6-pds/CMIP6...,<NA>,20191108
2,CMIP,AWI,AWI-CM-1-1-MR,historical,r1i1p1f1,day,tas,gn,osdf:///aws-opendata/us-west-2/cmip6-pds/CMIP6...,<NA>,20181218
3,ScenarioMIP,AWI,AWI-CM-1-1-MR,ssp370,r1i1p1f1,day,tas,gn,osdf:///aws-opendata/us-west-2/cmip6-pds/CMIP6...,<NA>,20190529
4,CMIP,BCC,BCC-CSM2-MR,historical,r1i1p1f1,day,tas,gn,osdf:///aws-opendata/us-west-2/cmip6-pds/CMIP6...,<NA>,20181126

In [15]:
df['activity_id'].unique()

<ArrowExtensionArray>
['CMIP', 'ScenarioMIP', 'AerChemMIP']
Length: 3, dtype: large_string[pyarrow]

In [16]:
# Keep only rows with CMIP (historical) or ScenarioMIP (ssp370) for consistency. 
df_filtered = col_subset.df[col_subset.df['activity_id'].isin(['CMIP', 'ScenarioMIP'])]

print("Filtered DataFrame shape:", df_filtered.shape)
# print("Filtered activity_id values:", df_filtered['activity_id'])

Filtered DataFrame shape: (53, 11)

In [17]:
df_filtered.groupby("source_id")[["experiment_id", "variable_id", "table_id","activity_id"]].nunique()

                   experiment_id  variable_id  table_id  activity_id
source_id
ACCESS-CM2                     2            1         1            2
AWI-CM-1-1-MR                  2            1         1            2
BCC-CSM2-MR                    2            1         1            2
BCC-ESM1                       1            1         1            1
CESM2-WACCM                    2            1         1            2
CMCC-CM2-SR5                   2            1         1            2
CMCC-ESM2                      2            1         1            2
CanESM5                        2            1         1            2
EC-Earth3                      2            1         1            2
EC-Earth3-AerChem              2            1         1            2
EC-Earth3-Veg                  2            1         1            2
EC-Earth3-Veg-LR               2            1         1            2
FGOALS-g3                      2            1         1            2
GFDL-ESM4                      2            1         1            2
IITM-ESM                       2            1         1            2
INM-CM4-8                      2            1         1            2
INM-CM5-0                      2            1         1            2
IPSL-CM5A2-INCA                2            1         1            2
IPSL-CM6A-LR                   2            1         1            2
KACE-1-0-G                     2            1         1            2
MIROC6                         2            1         1            2
MPI-ESM-1-2-HAM                2            1         1            2
MPI-ESM1-2-HR                  2            1         1            2
MPI-ESM1-2-LR                  2            1         1            2
MRI-ESM2-0                     2            1         1            2
NorESM2-LM                     2            1         1            2
NorESM2-MM                     2            1         1            2

In [18]:
%%time
# dsets = col_subset.to_dataset_dict(storage_options={'anon': 'True'})
dsets = col_subset.to_dataset_dict()
print(f"\nDataset dictionary keys:\n {dsets.keys()}")

--> The keys in the returned dictionary of datasets are constructed as follows:
	'activity_id.institution_id.source_id.experiment_id.table_id.grid_label'

```html
<div>
<progress max="54" value="54"></progress> 100.00% [54/54 00:30&lt;00:00]</div>

```

/home/ncote/miniforge3/envs/nb-env/lib/python3.13/site-packages/intake_esm/source.py:109: RuntimeWarning: Failed to open Zarr store with consolidated metadata, but successfully read with non-consolidated metadata. This is typically much slower for opening a dataset. To silence this warning, consider:
1. Consolidating metadata in this existing store with zarr.consolidate_metadata().
2. Explicitly setting consolidated=False, to avoid trying to read consolidate metadata, or
3. Explicitly setting consolidated=True, to raise an error in this case instead of falling back to try reading non-consolidated metadata.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/home/ncote/miniforge3/envs/nb-env/lib/python3.13/site-packages/intake_esm/source.py:109: RuntimeWarning: Failed to open Zarr store with consolidated metadata, but successfully read with non-consolidated metadata. This is typically much slower for opening a dataset. To silence this warning, consider:
1. Consolidating metadata in this existing store with zarr.consolidate_metadata().
2. Explicitly setting consolidated=False, to avoid trying to read consolidate metadata, or
3. Explicitly setting consolidated=True, to raise an error in this case instead of falling back to try reading non-consolidated metadata.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/home/ncote/miniforge3/envs/nb-env/lib/python3.13/site-packages/intake_esm/source.py:109: RuntimeWarning: Failed to open Zarr store with consolidated metadata, but successfully read with non-consolidated metadata. This is typically much slower for opening a dataset. To silence this warning, consider:
1. Consolidating metadata in this existing store with zarr.consolidate_metadata().
2. Explicitly setting consolidated=False, to avoid trying to read consolidate metadata, or
3. Explicitly setting consolidated=True, to raise an error in this case instead of falling back to try reading non-consolidated metadata.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/home/ncote/miniforge3/envs/nb-env/lib/python3.13/site-packages/intake_esm/source.py:109: RuntimeWarning: Failed to open Zarr store with consolidated metadata, but successfully read with non-consolidated metadata. This is typically much slower for opening a dataset. To silence this warning, consider:
1. Consolidating metadata in this existing store with zarr.consolidate_metadata().
2. Explicitly setting consolidated=False, to avoid trying to read consolidate metadata, or
3. Explicitly setting consolidated=True, to raise an error in this case instead of falling back to try reading non-consolidated metadata.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/home/ncote/miniforge3/envs/nb-env/lib/python3.13/site-packages/intake_esm/source.py:109: RuntimeWarning: Failed to open Zarr store with consolidated metadata, but successfully read with non-consolidated metadata. This is typically much slower for opening a dataset. To silence this warning, consider:
1. Consolidating metadata in this existing store with zarr.consolidate_metadata().
2. Explicitly setting consolidated=False, to avoid trying to read consolidate metadata, or
3. Explicitly setting consolidated=True, to raise an error in this case instead of falling back to try reading non-consolidated metadata.
  ds = xr.open_dataset(url, **xarray_open_kwargs)

Dataset dictionary keys:
 dict_keys(['CMIP.MRI.MRI-ESM2-0.historical.day.gn', 'CMIP.EC-Earth-Consortium.EC-Earth3-Veg.historical.day.gr', 'CMIP.EC-Earth-Consortium.EC-Earth3-AerChem.historical.day.gr', 'ScenarioMIP.EC-Earth-Consortium.EC-Earth3-AerChem.ssp370.day.gr', 'CMIP.NOAA-GFDL.GFDL-ESM4.historical.day.gr1', 'ScenarioMIP.CCCma.CanESM5.ssp370.day.gn', 'CMIP.INM.INM-CM5-0.historical.day.gr1', 'CMIP.EC-Earth-Consortium.EC-Earth3.historical.day.gr', 'ScenarioMIP.NCAR.CESM2-WACCM.ssp370.day.gn', 'ScenarioMIP.HAMMOZ-Consortium.MPI-ESM-1-2-HAM.ssp370.day.gn', 'ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp370.day.gn', 'CMIP.MPI-M.MPI-ESM1-2-LR.historical.day.gn', 'ScenarioMIP.INM.INM-CM5-0.ssp370.day.gr1', 'ScenarioMIP.NOAA-GFDL.GFDL-ESM4.ssp370.day.gr1', 'CMIP.NIMS-KMA.KACE-1-0-G.historical.day.gr', 'CMIP.CMCC.CMCC-ESM2.historical.day.gn', 'ScenarioMIP.EC-Earth-Consortium.EC-Earth3.ssp370.day.gr', 'CMIP.MPI-M.MPI-ESM1-2-HR.historical.day.gn', 'ScenarioMIP.CMCC.CMCC-CM2-SR5.ssp370.day.gn', 'CMIP.CAS.FGOALS-g3.historical.day.gn', 'CMIP.NCC.NorESM2-LM.historical.day.gn', 'CMIP.AWI.AWI-CM-1-1-MR.historical.day.gn', 'CMIP.INM.INM-CM4-8.historical.day.gr1', 'ScenarioMIP.CAS.FGOALS-g3.ssp370.day.gn', 'ScenarioMIP.BCC.BCC-CSM2-MR.ssp370.day.gn', 'ScenarioMIP.CCCR-IITM.IITM-ESM.ssp370.day.gn', 'CMIP.NCC.NorESM2-MM.historical.day.gn', 'ScenarioMIP.CSIRO-ARCCSS.ACCESS-CM2.ssp370.day.gn', 'ScenarioMIP.AWI.AWI-CM-1-1-MR.ssp370.day.gn', 'ScenarioMIP.INM.INM-CM4-8.ssp370.day.gr1', 'ScenarioMIP.MRI.MRI-ESM2-0.ssp370.day.gn', 'ScenarioMIP.NCC.NorESM2-LM.ssp370.day.gn', 'ScenarioMIP.MIROC.MIROC6.ssp370.day.gn', 'CMIP.BCC.BCC-ESM1.historical.day.gn', 'CMIP.IPSL.IPSL-CM6A-LR.historical.day.gr', 'CMIP.CMCC.CMCC-CM2-SR5.historical.day.gn', 'CMIP.CCCma.CanESM5.historical.day.gn', 'ScenarioMIP.NCC.NorESM2-MM.ssp370.day.gn', 'ScenarioMIP.EC-Earth-Consortium.EC-Earth3-Veg-LR.ssp370.day.gr', 'ScenarioMIP.EC-Earth-Consortium.EC-Earth3-Veg.ssp370.day.gr', 'CMIP.MIROC.MIROC6.historical.day.gn', 'CMIP.HAMMOZ-Consortium.MPI-ESM-1-2-HAM.historical.day.gn', 'CMIP.CSIRO-ARCCSS.ACCESS-CM2.historical.day.gn', 'AerChemMIP.BCC.BCC-ESM1.ssp370.day.gn', 'ScenarioMIP.NIMS-KMA.KACE-1-0-G.ssp370.day.gr', 'ScenarioMIP.IPSL.IPSL-CM6A-LR.ssp370.day.gr', 'ScenarioMIP.DKRZ.MPI-ESM1-2-HR.ssp370.day.gn', 'CMIP.IPSL.IPSL-CM5A2-INCA.historical.day.gr', 'CMIP.EC-Earth-Consortium.EC-Earth3-Veg-LR.historical.day.gr', 'ScenarioMIP.CMCC.CMCC-ESM2.ssp370.day.gn', 'CMIP.NCAR.CESM2-WACCM.historical.day.gn', 'CMIP.CCCR-IITM.IITM-ESM.historical.day.gn', 'CMIP.BCC.BCC-CSM2-MR.historical.day.gn', 'ScenarioMIP.IPSL.IPSL-CM5A2-INCA.ssp370.day.gr'])
CPU times: user 3.81 s, sys: 891 ms, total: 4.7 s
Wall time: 30.7 s

In [19]:
def drop_all_bounds(ds):
    drop_vars = [vname for vname in ds.coords
                 if (('_bounds') in vname ) or ('_bnds') in vname]
    return ds.drop_vars(drop_vars)

def open_dset(df):
    assert len(df) == 1
    
    # Force anonymous access for public datasets
    storage_options = {'anon': True}
    # ds = xr.open_zarr(fsspec.get_mapper(df.zstore.values[0], **storage_options),consolidated=True) #For s3fs protocol
    ds = xr.open_zarr(fsspec.get_mapper(df.zstore.values[0]), consolidated=True) #Use for PelicanFS
    return drop_all_bounds(ds)

def open_delayed(df):
    return dask.delayed(open_dset)(df)

from collections import defaultdict
dsets = defaultdict(dict)

for group, df in col_subset.df.groupby(by=['source_id', 'experiment_id']):
    dsets[group[0]][group[1]] = open_delayed(df)

NameError: name 'dask' is not defined

In [ ]:
%%time
# Trigger computation
dsets_ = dask.compute(dict(dsets))[0]

In [ ]:
#Define coarse grid to regrid on 1 *1 degree card
ds_out = xr.Dataset({'lat': (['lat'], np.arange(-90, 91, 1.5)),
                    'lon': (['lon'], np.arange(0, 361, 1.5))})
ds_out

In [ ]:
def drop_feb29(ds):
    # Check if the dataset's calendar is not '360_day'
    calendar = ds.time.encoding.get('calendar', None)
    print(ds.attrs['source_id'],calendar)
    if calendar != '360_day':
        ds = ds.convert_calendar('365_day')
    return ds


def to_daily(ds):
    # Check and deal with different datetime types
    if isinstance(ds['time'].values[0], np.datetime64):
        pass
    elif isinstance(ds['time'].values[0], cftime.datetime):
        pass
    else:
        # convert time coordinate to datetime64 objects
        ds['time'] = ds['time'].astype('datetime64[ns]')
    year      = ds.time.dt.year
    dayofyear = ds.time.dt.dayofyear

    # assign new coords
    ds = ds.assign_coords(year=("time", year.data), dayofyear=("time", dayofyear.data))

    # reshape the array to (..., "day", "year")
    return ds.set_index(time=("year", "dayofyear")).unstack("time")  


def extract_data(ds):
    """
    Extract data from the dataset 'ds' for specific time and spatial range.

    Parameters:
    - ds (xarray.Dataset): Input dataset

    Returns:
    - xarray.Dataset: Dataset subsetted for required years and the specified space and time range.
    """    

    subset1 = ds.sel(year=slice(1850, 1879))
    subset2 = ds.sel(year=slice(2071, 2100))
    
    subset = xr.concat([subset1, subset2], dim='year')  

    return subset

def is_leap(year):
    """Check if a year is a leap year."""
    return (year % 4 == 0) and ((year % 100 != 0) or (year % 400 == 0))

In [ ]:
quants = np.linspace(0,1.0,30)

def compute_quantiles(ds, quantiles=quants):
    return ds.chunk(dict(year=-1)).quantile(quantiles, dim='year',skipna=False)

def regrid(ds, ds_out):
    experiment_id = ds.attrs['experiment_id']
    source_id     = ds.attrs['source_id']
    ds_new   = ds.regrid.nearest(ds_out)
    
#     #Assign back attributes as regirdder would have deleted attributes 
    ds_new.attrs['experiment_id'] = experiment_id
    ds_new.attrs['source_id'] = source_id
    
    #print(ds_new.attrs['experiment_id'],ds_new.attrs['source_id'])
    #print(ds_new)
    return ds_new

def process_data(ds, quantiles=quants):
    ds = ds.pipe(drop_feb29).pipe(to_daily).pipe(extract_data)
    
    if len(ds['year']) == 0:
        print("The dataset is empty. Skipping...")
        return None
    
    if len(ds['dayofyear'])<365:
        print('The dataset has less than 365 days. Skipping ..')
        return None
    
    # # Remove 'time' coordinate
    # ds = ds.set_index(time=("year", "dayofyear")).unstack("time")  
    return (ds.pipe(regrid, ds_out=ds_out))

## Section 3: Computations. 
- Evalulate these

In [ ]:
%%time
if RECALC:
    with progress.ProgressBar():
    
        expt_da = xr.DataArray(expts, dims='experiment_id', name='experiment_id',
                               coords={'experiment_id': expts})
    
        # Initialize an Empty Dictionary for Aligned Datasets:
        dsets_aligned = {}
    
        # Iterate Over dsets_ Dictionary:
    
        for k, v in tqdm(dsets_.items()):
            # Initialize a dictionary for this source_id
            dsets_aligned[k] = {}
            
            skip_source_id = False
    
            for expt in expts:
                ds = v[expt].pipe(process_data)
    
                # Check if the dataset is empty and skip this source_id if so
                if ds is None:
                    print(f"Skipping {expt} for {k} because the dataset is empty")
                    skip_source_id = True
                    break
                
                # Store the dataset in the dictionary
                # dsets_aligned[k][expt] = ds
                # Compute the dataset and store it in the dictionary
                dsets_aligned[k][expt] = ds.compute()
                print(dsets_aligned[k][expt])
    
            if skip_source_id:
                del dsets_aligned[k]
                continue

In [ ]:
# dsets_aligned.keys()

In [ ]:
%%time
if RECALC:
    source_ids = list(dsets_aligned.keys())
    source_da = xr.DataArray(source_ids, dims='source_id', name='source_id',
                         coords={'source_id': source_ids})
    final_ds_pi = xr.concat([ds['historical'].reset_coords(drop=True)
                                     for ds in dsets_aligned.values()],
                                    dim=source_da)
    
    final_ds_eoc = xr.concat([ds['ssp370'].reset_coords(drop=True)
                                 for ds in dsets_aligned.values()],
                                dim=source_da)
    final_ds_eoc

In [ ]:
%%time
final_ds_pi.to_zarr(folder_path  +'cmip6_pi_daily.zarr',mode='w')
final_ds_eoc.to_zarr(folder_path +'cmip6_eoc_daily.zarr',mode='w')

In [ ]:
final_ds_pi  = xr.open_zarr(folder_path+'cmip6_pi_daily.zarr')
final_ds_eoc = xr.open_zarr(folder_path+'cmip6_eoc_daily.zarr')
final_ds_pi  = final_ds_pi[var_name]
final_ds_eoc = final_ds_eoc[var_name]
final_ds_eoc

### Detrend data and save

In [ ]:
%%time
ds_pi_det  = detrend_data(final_ds_pi,pi_year)
ds_eoc_det = detrend_data(final_ds_eoc,eoc_year)
ds_eoc_det = ds_eoc_det.chunk({'year':30,'source_id':1})
ds_pi_det = ds_pi_det.chunk({'year':30,'source_id':1})
ds_eoc_det

In [ ]:
# %%time
# ds_pi_det.rename(var_name).to_dataset().to_zarr(folder_path  +'cmip6_pi_ann_detrended.zarr',mode='w')

In [ ]:
# %%time
# ds_eoc_det.rename(var_name).to_dataset().to_zarr(folder_path +'cmip6_eoc_ann_detrended.zarr',mode='w')

### Check if detrending worked

In [ ]:
ds_pi_det  = xr.open_zarr(folder_path  +'cmip6_pi_ann_detrended.zarr')
ds_eoc_det = xr.open_zarr(folder_path +'cmip6_eoc_ann_detrended.zarr')
#
ds_pi_det  = ds_pi_det[var_name]
ds_eoc_det = ds_eoc_det[var_name]

In [ ]:
%%time
ds_pi_det.sel(lat=chic_lat,lon=chic_lon,method='nearest').sel(dayofyear=2).mean('source_id').plot()
final_ds_pi.sel(lat=chic_lat,lon=chic_lon,method='nearest').sel(dayofyear=2).mean('source_id').plot()

In [ ]:
%%time
ds_eoc_det.sel(lat=chic_lat,lon=chic_lon,method='nearest').sel(dayofyear=2).mean('source_id').plot()
final_ds_eoc.sel(lat=chic_lat,lon=chic_lon,method='nearest').sel(dayofyear=2).mean('source_id').plot()